---
title: "Consistency tests"
author: "LMM"
date: "17 de julio de 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(asnipe)
library(igraph)
library(linkcomm)
source('R/cmbDFrame.r')
source('R/rcomm_exx.r')
source('R/new_exy_calculation.r')
source('R/Permutational_community_assortativity.r')
source('R/adj_to_edgelist.r')
source('R/xy_subsets.r')
data('identified_individuals')
```
The following are the data used in [Shizuka et al. (2016)](https://www.sciencedirect.com/science/article/pii/S0003347215004480?via%3Dihub)

```{r original datasets}
sparrow <- read.csv(url('https://datadryad.org/bitstream/handle/10255/dryad.63926/Flock_Season3_Dryad.csv'), na.strings = c('NA', ' ', ''))

tit <- identified_individuals[identified_individuals$Date == 1,]

thornbill <- read.csv('data/mmc1.csv')
```

#1. Sparrow data

```{r sparrow data}
sparrow_el <- sparrow %>% 
    select(-c(1:3)) %>%
    cmbDFrame()

sparrow_wel <- sparrow_el$mrgCCombs %>% 
    data.frame() %>%
    mutate(X1 = as.character(X1), X2 = as.character(X2))
```

```{r sparrow simple ratio association index}
sparrow_wel$weight <- 0

for(i in 1:nrow(unique(sparrow_wel))) {
    RowsOcurrency <- rowSums(t(apply(sparrow_wel, 1, function(x) x %in%  unique(sparrow_wel)[i, ]))) == 2
    
    A <- sum(RowsOcurrency)


    if(unique(sparrow_wel)[i, 2] == "") {
        B <- sum(sparrow_wel == unique(sparrow_wel)[i, 1])
        } else {
         B <- sum(sparrow_wel == unique(sparrow_wel)[i, 1],
             sparrow_wel == unique(sparrow_wel)[i, 2])   
        }

    ##we apply the operation A/(B-A) given that by calculating the sum of the frecuency of A and B we are adding twice the value of the interaction A*B.
    sparrow_wel$weight[RowsOcurrency] <- A/(B-A)

print(paste(round(100*i/nrow(unique(sparrow_wel)), 1), "%"))
}

sparrow_wel <- sparrow_wel[sparrow_wel$X2 != '',] #Discard solitary individuals
```

```{r sparrow graphs}
sparrow_g <- graph_from_data_frame(sparrow_wel, directed = FALSE) 

sparrow_g <- simplify(sparrow_g)#Discard multiple edges

sparrow_dis <- cluster_fast_greedy(sparrow_g) #discrete communities
#plot(sparrow_comm, sparrow_g)

sparrow_over <- getLinkCommunities(sparrow_wel) #overlapping communities
#plotLinkCommGraph(sparrow_over)
```

Now we can compare the consistency of the proposed metric

```{r sparrow rcomx}
Pij_comm <- calc_Pmatrix(sparrow_g, 100)

Exx <- rcomm_exx(Pij_comm)
Exy <- rcom_exy()

rcom_spa <- (Exx - Exy)/(1 - Exy)
print(rcom_spa)
```

